# Generated by Django 3.1.3 on 2020-12-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201213_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='overview',
            new_name='content',
        ),
    ]
