# Generated by Django 3.1.3 on 2020-12-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='view_count',
        ),
    ]
