# Generated by Django 3.1.3 on 2020-12-17 09:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='ahmed'),
            preserve_default=False,
        ),
    ]
