# Generated by Django 3.1.3 on 2020-12-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
    ]
