# Generated by Django 3.1.3 on 2020-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_post_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(default='goooood'),
            preserve_default=False,
        ),
    ]
