# Generated by Django 3.1.3 on 2020-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_post_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.CharField(max_length=100),
        ),
    ]
